# Generated by Django 4.2.19 on 2026-06-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMSymbolKraken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(blank=True, default=0, null=True)),
                ('symbol', models.CharField(db_column='symbol', max_length=255)),
                ('symbol_call', models.CharField(db_column='symbol_call', default='', max_length=255)),
                ('auto_flag', models.CharField(db_column='auto_flag', default='0', max_length=10)),
                ('tr_price', models.DecimalField(decimal_places=18, default=0, max_digits=31)),
                ('tr_qty', models.DecimalField(decimal_places=18, default=0, max_digits=31)),
                ('tr_time', models.BigIntegerField(db_column='tr_time', default=0)),
                ('deleted_flag', models.BooleanField(default=False, verbose_name='사용여부')),
            ],
            options={
                'db_table': 'atm_symbol_kraken',
            },
        ),
    ]
